### PR TITLE
Reset window size to what it was before it was snapped - addresses #4

### PR DESCRIPTION
**Pull request by JoeyEamigh**
Hey!!

Thanks for your hard work on this project! I have added a little quality of life feature mimicking the Rectangle Mac feature which resizes the window back to its original size when unsnapped. This addresses #4.

I attempted to maintain your code style for these changes.

One thing to note: when the window resizes after being unsnapped, it shoots itself to the left corner. Not sure of the best way to fix it for the moment, but I did find <https://invent.kde.org/plasma/kwin/-/merge_requests/3134> which will allow for KWin scripts to get the position of the cursor, and as a result allow for the window to be set to the cursor's position, eliminating this one issue with the unsnap.

It was merged 3 weeks ago, but was not backported to Plasma 5.26.3, so I am unable to get a conditional feature working yet. I may compile from source and check it out, but if not, I will add this feature when Plasma 5.27 goes gold.

Let me know your thoughts on this PR!

### CODE REVIEW

**Comment by acristoffers** [comment]
Thank you for your work on this. It seems everything is fine, I'll test it tonight and see how bad is the jump to the side. I believe that the version published should have this polished, so we either find a way to make this smooth or wait for the merge to be backported. But either way this will get merged at some point :)

**Comment by acristoffers** [comment]
I could not reproduce the bug with the window shooting to the left corner, for me it is working just fine.

**Comment by JoeyEamigh** [comment]
May have described that wrong - it definitely doesn't shoot to the left corner, but the drag starts from the top left corner of the screen, meaning that every now and then if you take a window that was fairly small before being snapped and drag it from the right side, the mouse may not be touching the window for the initial grab. Very minor cosmetic thing more than an actual issues. Glad you aren't seeing any issues though!! Big fan of this project.

**Comment by acristoffers** [comment]
Well, that is better than the shoot-to-the-left I imagined, so I'm going ahead and merging/publishing this since the behavior is not so bad.

**Pull request merged**
